adv_works:
  outputs:
    dev:
      account: uxlvgjn-qj59414
      database: HR
      password: Rpj872urt687@
      role: DBT_RW
      schema: MODEL
      threads: 1
      type: snowflake
      user: MARCMEDAWAR14
      warehouse: ETL
  target: dev
dbtlearn:
  outputs:
    dev:
      account: ewezplm-no66906
      database: airbnb
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 4
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
dbtlearn2:
  outputs:
    dev:
      account: ewezplm-no66906
      database: airbnb
      password: dbtPassword123
      role: tranform
      schema: dev
      threads: 4
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
premierleague:
  outputs:
    dev:
      account: uxlvgjn-qj59414
      database: football_db
      password: Rpj872urt687@
      role: dbt
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: MARCMEDAWAR14
      warehouse: football_wh
  target: dev
